import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import localFont from "next/font/local";
export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const budaLight = localFont({
  src: "./_assets/Buda-Light.ttf",
  variable: "--font-buda",
});

const missPhilips = localFont({
  src: "./_assets/Miss-Phillips.ttf",
  variable: "--font-phillips",
});

const nunito = localFont({
  src: "./_assets/NunitoSans.ttf",
  variable: "--font-nunito",
});

const NunitoSansItalic = localFont({
  src: "./_assets/NunitoSans-Italic.ttf",
  variable: "--font-nunito-italic",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${GeistSans.variable} ${budaLight.variable} ${missPhilips.variable} ${nunito.variable} ${NunitoSansItalic.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
