// app/layout.tsx

import "~/styles/globals.css";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import localFont from "next/font/local";
import { Toaster } from "~/components/ui/toaster";
import Providers from "./providers";
import Head from "next/head"; // Import Head for adding meta tags

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const lagency = localFont({
  src: "./_assets/fonts/Lagency-Regular.woff2",
  variable: "--font-lagency",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <>
      <Head>
        <link href="https://fonts.googleapis.com/css2?family=Lora:wght@400;700&display=swap" rel="stylesheet" />
      </Head>
      <html lang="en" className={`${GeistSans.variable} ${lagency.variable}`}>
        <body className="font-lora"> {/* Apply Lora font to body */}
          <Providers>{children}</Providers>
          <Toaster />
        </body>
      </html>
    </>
  );
}
